import argparse

parser = argparse.ArgumentParser(description="R2GenGPT 的超参数")
parser.add_argument('--test', action='store_true', help="仅运行测试集")
parser.add_argument('--validate', action='store_true', help="仅运行验证集")
parser.add_argument('--dataset', type=str, default='mimic_cxr', help="数据集: iu-xray 或 mimic-cxr")
parser.add_argument('--annotation', type=str, default=r'/root/autodl-tmp/mimic_cxr_mini/p10_annotation_final.json', help="数据集的标注文件")
parser.add_argument('--base_dir', type=str, default=r'/root/autodl-tmp/mimic_cxr_mini/images', help="图像的基础目录")
parser.add_argument('--batch_size', default=6, type=int, help="每个 worker 的训练批次大小")
parser.add_argument('--val_batch_size', default=16, type=int, help="每个 worker 的验证批次大小")
parser.add_argument('--test_batch_size', default=16, type=int, help="每个 worker 的测试批次大小")
parser.add_argument('--prefetch_factor', default=4, type=int, help="每个 worker 的预取因子")
parser.add_argument('--num_workers', default=8, type=int, help="数据加载器的 CPU 核心数")
parser.add_argument('--image_save_path', type=str, default=r'/root/autodl-tmp/save', help="测试时保存图像的路径")
parser.add_argument('--vision_model', default='microsoft/swin-base-patch4-window7-224', type=str, help="使用的视觉模型")
parser.add_argument('--llama_model', default='meta-llama/Llama-2-7b-chat-hf', type=str, help="使用的语言模型")
parser.add_argument('--freeze_vm', default=True, type=lambda x: (str(x).lower() == 'true'), help='是否冻结视觉模型')
parser.add_argument('--llm_use_lora', default=False, type=lambda x: (str(x).lower() == 'true'), help="是否为语言模型使用 LoRA")
parser.add_argument('--llm_r', default=16, type=int, help='LoRA 更新矩阵的维度')
parser.add_argument('--llm_alpha', default=16, type=int, help='LoRA 缩放因子')
parser.add_argument('--vis_use_lora', default=False, type=lambda x: (str(x).lower() == 'true'), help="是否为视觉模型使用 LoRA")
parser.add_argument('--vis_r', default=16, type=int, help='视觉模型 LoRA 更新矩阵的维度')
parser.add_argument('--vis_alpha', default=16, type=int, help='视觉模型 LoRA 缩放因子')
parser.add_argument('--lora_dropout', default=0.1, type=float, help='LoRA 的 dropout 率')
parser.add_argument('--global_only', default=False, type=lambda x: (str(x).lower() == 'true'), help='仅使用全局嵌入')
parser.add_argument('--low_resource', default=False, type=bool)
parser.add_argument('--end_sym', default='</s>', type=str)
parser.add_argument('--savedmodel_path', type=str, default='/root/autodl-tmp/save/mimic/v1')
parser.add_argument('--ckpt_file', type=str, default=None, help='要加载的检查点文件')
parser.add_argument('--delta_file', type=str, default=None, help='要加载的增量文件')
parser.add_argument('--weights', type=list, default=[0.5, 0.5])
parser.add_argument('--scorer_types', type=list, default=['Bleu_4', 'CIDEr'])
parser.add_argument('--learning_rate', default=1e-4, type=float, help='初始学习率')
parser.add_argument('--gradient_clip_val', default=None, type=int, help='梯度裁剪值')
parser.add_argument('--beam_size', type=int, default=3)
parser.add_argument('--do_sample', type=bool, default=False)
parser.add_argument('--no_repeat_ngram_size', type=int, default=2)
parser.add_argument('--num_beam_groups', type=int, default=1)
parser.add_argument('--min_new_tokens', type=int, default=80)
parser.add_argument('--max_new_tokens', type=int, default=120)
parser.add_argument('--max_length', type=int, default=100)
parser.add_argument('--repetition_penalty', type=float, default=2.0)
parser.add_argument('--length_penalty', type=float, default=2.0)
parser.add_argument('--diversity_penalty', type=float, default=0)
parser.add_argument('--temperature', type=float, default=0)
parser.add_argument('--devices', type=int, default=1, help='使用的 GPU 数量')
parser.add_argument('--num_nodes', type=int, default=1, help='分布式训练的 GPU 节点数')
parser.add_argument('--accelerator', type=str, default="gpu", choices=["cpu", "gpu", "tpu", "ipu", "hpu", "mps"], help='加速器类型')
parser.add_argument('--strategy', type=str, default="ddp", help='默认使用 ddp 进行多 GPU 训练')
parser.add_argument('--precision', type=str, default='bf16-mixed', help='精度: 16 或 32 或 bf16-mixed')
parser.add_argument('--limit_val_batches', type=float, default=1.0, help='验证集检查的比例')
parser.add_argument('--limit_test_batches', type=float, default=1.0, help='测试集检查的比例')
parser.add_argument('--limit_train_batches', type=float, default=1.0, help='训练集检查的比例')
parser.add_argument('--max_epochs', type=int, default=3, help='最大训练轮数')
parser.add_argument('--every_n_train_steps', type=int, default=0, help='每多少训练步保存一次检查点')
parser.add_argument('--val_check_interval', type=float, default=1.0, help='验证集检查的频率')
parser.add_argument('--accumulate_grad_batches', type=int, default=1, help='梯度累积的批次数')
parser.add_argument("--num_sanity_val_steps", type=int, default=2, help='训练前验证的批次数')
parser.add_argument('--task', type=str, default='classification', choices=['report', 'classification'], help="任务类型: 'report' 表示报告生成，'classification' 表示疾病分类")