import argparse

parser = argparse.ArgumentParser(description="Hyperparameters for R2GenGPT")
parser.add_argument('--test', action='store_true', help="Only run the test set")
parser.add_argument('--validate', action='store_true', help="Only run the validation set")
parser.add_argument('--dataset', type=str, default='mimic_cxr', help="Dataset: iu-xray or mimic-cxr")
parser.add_argument('--annotation', type=str, default=r'/root/autodl-tmp/mimic_cxr_mini/p10_annotation_final.json', help="Annotation file of the dataset")
parser.add_argument('--base_dir', type=str, default=r'/root/autodl-tmp/mimic_cxr_mini/images', help="Base directory for images")
parser.add_argument('--batch_size', default=6, type=int, help="Batch size per worker for training")
parser.add_argument('--val_batch_size', default=16, type=int, help="Batch size per worker for validation")
parser.add_argument('--test_batch_size', default=16, type=int, help="Batch size per worker for testing")
parser.add_argument('--prefetch_factor', default=4, type=int, help="Prefetch factor per worker")
parser.add_argument('--num_workers', default=8, type=int, help="Number of CPU cores for data loaders")
parser.add_argument('--image_save_path', type=str, default=r'/root/autodl-tmp/save', help="Path to save images during testing")
parser.add_argument('--save_images', action='store_true', help="Save images and text comparisons during validation for each epoch")
parser.add_argument('--vision_model', default='microsoft/swin-base-patch4-window7-224', type=str, help="Vision model to use")
parser.add_argument('--llama_model', default='meta-llama/Llama-2-7b-chat-hf', type=str, help="Language model to use")
parser.add_argument('--freeze_vm', default=True, type=lambda x: (str(x).lower() == 'true'), help='Freeze the vision model')
parser.add_argument('--llm_use_lora', default=False, type=lambda x: (str(x).lower() == 'true'), help="Use LoRA for the language model")
parser.add_argument('--llm_r', default=16, type=int, help='LoRA update matrix dimension')
parser.add_argument('--llm_alpha', default=16, type=int, help='LoRA scaling factor')
parser.add_argument('--vis_use_lora', default=False, type=lambda x: (str(x).lower() == 'true'), help="Use LoRA for the vision model")
parser.add_argument('--vis_r', default=16, type=int, help='Vision model LoRA update matrix dimension')
parser.add_argument('--vis_alpha', default=16, type=int, help='Vision model LoRA scaling factor')
parser.add_argument('--lora_dropout', default=0.1, type=float, help='LoRA dropout rate')
parser.add_argument('--global_only', default=False, type=lambda x: (str(x).lower() == 'true'), help='Use global embeddings only')
parser.add_argument('--low_resource', default=False, type=bool)
parser.add_argument('--end_sym', default='</s>', type=str)
parser.add_argument('--savedmodel_path', type=str, default='/root/autodl-tmp/save/mimic/v1')
parser.add_argument('--ckpt_file', type=str, default=None, help='Checkpoint file to load')
parser.add_argument('--delta_file', type=str, default=None, help='Delta file to load')
parser.add_argument('--weights', type=list, default=[0.5, 0.5])
parser.add_argument('--scorer_types', type=list, default=['Bleu_4', 'CIDEr'])
parser.add_argument('--learning_rate', default=1e-4, type=float, help='Initial learning rate')
parser.add_argument('--gradient_clip_val', default=None, type=int, help='Gradient clipping value')
parser.add_argument('--beam_size', type=int, default=3)
parser.add_argument('--do_sample', type=bool, default=False)
parser.add_argument('--no_repeat_ngram_size', type=int, default=2)
parser.add_argument('--num_beam_groups', type=int, default=1)
parser.add_argument('--min_new_tokens', type=int, default=80)
parser.add_argument('--max_new_tokens', type=int, default=120)
parser.add_argument('--max_length', type=int, default=100)
parser.add_argument('--repetition_penalty', type=float, default=2.0)
parser.add_argument('--length_penalty', type=float, default=2.0)
parser.add_argument('--diversity_penalty', type=float, default=0)
parser.add_argument('--temperature', type=float, default=0)
parser.add_argument('--devices', type=int, default=1, help='Number of GPUs to use')
parser.add_argument('--num_nodes', type=int, default=1, help='Number of GPU nodes for distributed training')
parser.add_argument('--accelerator', type=str, default="gpu", choices=["cpu", "gpu", "tpu", "ipu", "hpu", "mps"], help='Accelerator type')
parser.add_argument('--strategy', type=str, default="ddp", help='Use ddp for multi-GPU training')
parser.add_argument('--precision', type=str, default='bf16-mixed', help='Precision: 16, 32, or bf16-mixed')
parser.add_argument('--limit_val_batches', type=float, default=1.0, help='Proportion of validation dataset to check')
parser.add_argument('--limit_test_batches', type=float, default=1.0, help='Proportion of test dataset to check')
parser.add_argument('--limit_train_batches', type=float, default=1.0, help='Proportion of training dataset to check')
parser.add_argument('--max_epochs', type=int, default=3, help='Maximum number of training epochs')
parser.add_argument('--every_n_train_steps', type=int, default=0, help='Save checkpoint every n training steps')
parser.add_argument('--val_check_interval', type=float, default=1.0, help='Frequency of validation checks')
parser.add_argument('--accumulate_grad_batches', type=int, default=1, help='Number of batches for gradient accumulation')
parser.add_argument("--num_sanity_val_steps", type=int, default=2, help='Number of validation batches before training')
parser.add_argument('--task', type=str, default='classification', choices=['report', 'classification'], help="Task type: 'report' or 'classification'")