import argparse

parser = argparse.ArgumentParser(description="Hyperparameters for R2GenGPT (Llama 3.2 3B)")

parser.add_argument('--vision_model', default='microsoft/swinv2-base-patch4-window16-256', type=str)
parser.add_argument('--llama_model', default='meta-llama/Llama-3.2-3B-Instruct', type=str)
parser.add_argument('--end_sym', default='<|eot_id|>', type=str)

parser.add_argument('--vis_use_lora', default=True, type=lambda x: (str(x).lower() == 'true'))
parser.add_argument('--vis_r', default=16, type=int)
parser.add_argument('--vis_alpha', default=16, type=int)
parser.add_argument('--vis_lora_target_modules', type=str, nargs='+', default=["query", "key", "value", "proj"])

parser.add_argument('--llm_use_lora', default=False, type=lambda x: (str(x).lower() == 'true'))
parser.add_argument('--llm_r', default=16, type=int)
parser.add_argument('--llm_alpha', default=16, type=int)
parser.add_argument('--lora_dropout', default=0.1, type=float)
parser.add_argument('--llm_lora_target_modules', type=str, nargs='+',
                    default=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"])

parser.add_argument('--test', action='store_true')
parser.add_argument('--validate', action='store_true')
parser.add_argument('--dataset', type=str, default='mimic_cxr')
# Ensure this path points to your actual combined annotation file
parser.add_argument('--annotation', type=str, default=r'/root/autodl-tmp/mimic_cxr/mimic_cxr_label_report_corrected.json')
parser.add_argument('--base_dir', type=str, default=r'/root/autodl-tmp/mimic_cxr/images')
parser.add_argument('--batch_size', default=8, type=int)
parser.add_argument('--val_batch_size', default=8, type=int)
parser.add_argument('--test_batch_size', default=4, type=int)
parser.add_argument('--prefetch_factor', default=4, type=int)
parser.add_argument('--num_workers', default=6, type=int)
parser.add_argument('--image_save_path', type=str, default=r'/root/autodl-tmp/save')
parser.add_argument('--save_images', action='store_true')
parser.add_argument('--freeze_vm', default=False, type=lambda x: (str(x).lower() == 'true'))
parser.add_argument('--low_resource', default=False, type=lambda x: (str(x).lower() == 'true'))
parser.add_argument('--savedmodel_path', type=str, default='/root/autodl-tmp/save/mimic/v1_L32_3B')
parser.add_argument('--ckpt_file', type=str, default=None)
parser.add_argument('--delta_file', type=str, default=None)
parser.add_argument('--learning_rate', default=2e-4, type=float)
parser.add_argument('--gradient_clip_val', default=1.0, type=float)

parser.add_argument('--beam_size', type=int, default=1)
parser.add_argument('--do_sample', default=False, type=lambda x: (str(x).lower() == 'true'))
parser.add_argument('--min_new_tokens', type=int, default=160)
parser.add_argument('--max_new_tokens', type=int, default=200)
parser.add_argument('--max_length', type=int, default=512)
parser.add_argument('--repetition_penalty', type=float, default=1.0)
parser.add_argument('--length_penalty', type=float, default=1.0)
parser.add_argument('--temperature', type=float, default=0.6)

parser.add_argument('--devices', type=int, default=1)
parser.add_argument('--num_nodes', type=int, default=1)
parser.add_argument('--accelerator', type=str, default="gpu", choices=["cpu", "gpu", "tpu", "ipu", "hpu", "mps"])
parser.add_argument('--strategy', type=str, default="auto")
parser.add_argument('--precision', type=str, default='bf16-mixed')
parser.add_argument('--limit_val_batches', type=float, default=1.0)
parser.add_argument('--limit_test_batches', type=float, default=1.0)
parser.add_argument('--limit_train_batches', type=float, default=1.0)
parser.add_argument('--max_epochs', type=int, default=5)
parser.add_argument('--val_check_interval', type=float, default=0.25)
parser.add_argument('--accumulate_grad_batches', type=int, default=2)
parser.add_argument("--num_sanity_val_steps", type=int, default=2)
# Ensure task is set correctly ('classification' or 'report')
parser.add_argument('--task', type=str, default='classification', choices=['classification', 'report'])
parser.add_argument('--pth_save_filename', type=str, default='best_model_weights.pth')
parser.add_argument('--seed', type=int, default=42)

# Add argument for enabling/disabling augmentations if needed
# parser.add_argument('--use_augmentation', default=True, type=lambda x: (str(x).lower() == 'true'), help="Enable/disable data augmentation for minority classes")

args = parser.parse_args()